apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendclient
  template:
    metadata:
      labels:
        app: frontendclient
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: frontendclient
      containers:
      - name: frontendclient
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/frontendclient/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: frontendclient-secret
          optional: true