apiVersion: apps/v1
kind: Deployment
metadata:
  name: anyclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anyclient
  template:
    metadata:
      labels:
        app: anyclient
      annotations:
        sidecar.istio.io/inject: "true"        
    spec:
      serviceAccountName: anyclient
      containers:
      - name: anyclient
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/anyclient/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: anyclient-secret
          optional: true